
server:
  port: 8088
  tomcat:
    threads:
      max: 50
logging:
  level:
    org.springframework: DEBUG



spring:
  messages:
    basename: messages

  jpa:
      show-sql: true

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

